### ISSUE TITLE
Question on field "version" of EntryMetaData

### ISSUE THREAD

**Issue by cioannid** [Kinetic/kinetic-java#17]
Hello community! I am interested in storing multiple versions of Entry objects. More specifically, instead of overwriting an object every time that it needs update, I would like to have one more version of that Entry instance.

Definitely, one way is forming a pattern in the key field which involves the actual key and the version of the object.

However, there is also the byte[] field "version" in EntryMetaData. I haven't managed to understand how it is used, though. I tried some examples but I end up with VersionMismatchException. Could someone describe the use case of the field "version"? It may fit in my case.

Thank you, Christos.

**Comment by jphughes** [comment]
> On May 22, 2015, at 1:04 AM, cioannid <notifications@github.com> wrote:
> 
> Hello. I am interested in storing multiple versions of Entry objects. More specifically, instead of overwriting an object every time that it needs update, I would like to have one more version of that Entry instance.
> 
> Definitely, one way is forming a pattern in the key field which involves the actual key and the version of the object.
> 
> However, there is also the byte[] field "version" in EntryMetaData. I haven't managed to understand how it is used, though. I tried some examples but I end up with VersionMismatchException. Could someone describe the use case of the field "version"? It may fit in my case.
> 

The version field is for the one and only value for this key. You can not write more than one value by changing the version. The version check is applied to the single key/value that you are attempting to replace. 

Your suggestion to form a pattern in the key field is the correct way of implementing this. 

Sincerely

Jim
