### ISSUE TITLE
mvn build fails when checked out into a directory named "kinetic"?

### ISSUE THREAD

**Issue by thomasknauth** [Kinetic/kinetic-java#37]
I'm seeing some weird behavior. Whenever I check out kinetic-java into a directory named "kinetic" in my home directory (Linux), building the project with 'mvn clean package' fails. As a side effect, the stuff inside the kinetic-java disappears. If checked out into, e.g., /tmp/kinetic, this doesn't happen. Tried it on two different machines, and with different users. Behavior is the same.

**Comment by chenchongli** [comment]
@thomasknauth Thank you for your comment!

"~/kinetic/" is the default Kinetic database home directory, when "mvn clean package" is executed, all the data in database will be cleaned(deleted). Please check out Kinetic/kinetic-java repository to a different directory to avoid this result when building kinetic-java via maven.  

Kinetic database home could be set by "-Dkinetic.home="kinetic_db_home_you_expected"" when you start a simulator by yourself. Please see the details in the following class:
https://github.com/Kinetic/kinetic-java/blob/master/kinetic-simulator/src/main/java/kinetic/simulator/SimulatorConfiguration.java

**Comment by thomasknauth** [comment]
Thanks for the switft response and confirming the issue.

After being bitten by this, I believe a comment in the README should be added. I spent hours trying to figure out what was wrong with my setup, until it finally dawned on me. I also believe ~/kinetic is a poor choice for the default db directory. Why not create a fresh temp dir for each mvn run?
